POST http://localhost:8082/products

{
    "name": "Product 3",
    "price": 103
}

###
GET http://localhost:8082/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjc0NjMxNjYsInN1YiI6IjFkYjE2NGZmLWZhMmItNDljMS1iOTAwLWQ4ZTQwOTQzY2UxNSJ9.yQ-zceyvHWWzmTx053i5MtGGsk9TE-MEUC92bj-rPZg

###
GET http://localhost:8082/products/33c2da1e-a8bd-4773-8a5f-bfc02c4ff608

###
PUT http://localhost:8082/products/33c2da1e-a8bd-4773-8a5f-bfc02c4ff609

{
    "name": "Product 999",
    "price": 999
}

###
DELETE http://localhost:8082/products/33c2da1e-a8bd-4773-8a5f-bfc02c4ff608

###
POST http://localhost:8082/users

{
    "name": "User 3",
    "email": "user3@user.com",
    "password": "1234563"
}

###
POST http://localhost:8082/users/token

{
    "email": "afif@test.com",
    "password": "Afif123456"
}

###
GET http://localhost:8082/docs/index.html