#simple mysql container
version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

# example of connection string
# jdbc:mysql://localhost:3306/test?user=test&password=test