GET http://localhost:8080/

###
GET http://localhost:8080/cep

###
GET http://localhost:8080/cep?cep=50760440

###
GET http://localhost:8080/afif

###
GET http://localhost:8080/index.html

###
GET http://localhost:8080/index